
site_name: Piloter la complexité technique
site_description: Gouvernance, architecture, pilotage et retours d'expérience
site_author: François Gay

markdown_extensions:
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js


theme:
  name: material
  language: fr
  favicon: assets/favicon.png

nav:


nav:
  - Accueil: index.md
  - Gouverner: gouverner/index.md
  - Architecturer: architecturer/index.md
  - Influencer: influencer/index.md
  - Capitaliser:
      - Acceuil: capitaliser/index.md
      - Visualiser, tracer, piloter : capitaliser/visualiser-tracer-piloter/index.md
  - RETEX: retex/index.md
  - Schémathèque:
      - Accueil: schematheque/index.md
      - Réseau:
          - Couches, composants et standards:
              schematheque/reseau/couches-composants-standards/index.md
