
site_name: Piloter la complexité technique
site_description: Gouvernance, architecture, pilotage et retours d'expérience
site_author: François Gay

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

          
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js


theme:
  name: material
  language: fr
  favicon: assets/favicon.png

nav:


nav:
  - Accueil: index.md
  - Architecturer: architecturer/index.md
  - Capitaliser:
      - Visualiser, tracer, piloter : capitaliser/visualiser-tracer-piloter/index.md
  - RETEX: retex/index.md
  - Schémathèque:
      - Accueil: schematheque/index.md
      - Réseau:
          - Couches, composants et standards:
              schematheque/reseau/couches-composants-standards/index.md
